### ISSUE TITLE
Display current price

### ISSUE THREAD

**Issue by steffentrommer** [eckonator/MMM-Oelpreise#1]
A long awaited plugin, thanks for that! One idea might be to display the price of the current day in a label.

**Comment by eckonator** [comment]
Yes nice idea. I myself not using this plugin at all, it's a fork as a request of a user who saw my pellet module and wanted to have this also for oil prices analog. Here we go :-)

So I don't donate any time to the further development of this module. But I am happy about a pull request with the wanted feature. Happy coding.
