### ISSUE TITLE
Price for every day in Graph

### ISSUE THREAD

**Issue by schrecki3000** [eckonator/MMM-Oelpreise#2]
Hello,
the graph looks very weird. It looks as if there would be a price displayed for every day in the graph:
![image](https://github.com/eckonator/MMM-Oelpreise/assets/135962513/507a4521-0cd3-442d-b8f2-b4f78f55040e)
Is it possible to remove this?

**Comment by eckonator** [comment]
I have never seen that before. Is it possible, that you using another MagicMirror plugin that is also based on "Chart.js" and possibly overrides the config settings for my module? Can you send me your complete config.js as private meesage?

**Comment by schrecki3000** [comment]
Yes of course, pls. tell me a Mail-Adress i can send it to. Thanks fordward for your support!
Regarding chart.js it may be MMM-WeatherChart...

**Comment by schrecki3000** [comment]
Hello Markus,

yes, of Course. You’ll find my config in the Attachment.
I think i already know which one. Your hint with Charts.js, i think it might be the „MMM-WeatherChart“…

Thanks Forward for your support!

Regards,
Philipp



Gesendet von Mail für Windows

Von: Markus
Gesendet: Donnerstag, 8. Juni 2023 20:48
An: eckonator/MMM-Oelpreise
Cc: schrecki3000; Author
Betreff: Re: [eckonator/MMM-Oelpreise] Price for every day in Graph (Issue #2)

I have never seen that before. Is it possible, that you using another MagicMirror plugin that is also based on "Chart.js" and possibly overrides the config settings for my module? Can you send me your complete config.js as private meesage?

**Comment by schrecki3000** [comment]
Hello Markus,

i think i already know which one it is after regarding your hint with Chart.js…
Maybe MMM-WeatherChart…

Here’s my anonymized config in the Attachment

Thanks for your support,
Regards Philipp


Gesendet von Mail für Windows

Von: Markus
Gesendet: Donnerstag, 8. Juni 2023 20:48
An: eckonator/MMM-Oelpreise
Cc: schrecki3000; Author
Betreff: Re: [eckonator/MMM-Oelpreise] Price for every day in Graph (Issue #2)

I have never seen that before. Is it possible, that you using another MagicMirror plugin that is also based on "Chart.js" and possibly overrides the config settings for my module? Can you send me your complete config.js as private meesage?
