### ISSUE TITLE
MagicMirror startete nicht nach Neuinstallation

### ISSUE THREAD

**Issue by surger13** [eckonator/MMM-Oelpreise#4]
Hallo,
ich musste das Modul neu installieren, da meine vorherige SD- Karte nicht mehr wollte.
Das ging am Ende nur, als ich aus der package.json unter dependencies ,"magicmirror-rebuild": "^1.0.5" entfernt habe. So läuft das Modul jetzt wieder und MagicMirror startet.

Neu:
`
 "dependencies": {
    "request": "latest",
    "chart.js": "^3.7.1"
  },

`

**Comment by eckonator** [comment]
Thanks for reporting. Bug is fixed in master branch.
